on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - uses: actions/cache@v6
        with:
          path: "**/node_modules"
          key: dev-${{ hashFiles('package-lock.json') }}
      - run: npm install
      - name: build
        run: npm run build
      - uses: actions/cache/save@v6
        with:
          path: packages/**/dist
          key: dist-${{ github.sha }}

  lint:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - uses: actions/cache@v6
        with:
          path: "**/node_modules"
          key: dev-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v6
        with:
          path: "**/node_modules"
          key: dev-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache/restore@v6
        with:
          path: packages/**/dist
          key: dist-${{ github.sha }}
      - name: lint
        run: npm run lint
      - name: check
        run: npm run eslint:fix

  # TODO テストコード書く
  # test:
  #   needs:
  #     - build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: actions/setup-node@v6
  #       with:
  #         node-version: 22
  #     - uses: actions/cache@v5
  #       with:
  #         path: "**/node_modules"
  #         key: prd-${{ hashFiles('**/package-lock.json') }}
  #     - uses: actions/cache/restore@v5
  #       with:
  #         path: packages/**/dist
  #         key: dist-${{ github.sha }}
  #     - name: Install only production dependencies
  #       run: npm install --production
  #     - name: test
  #       run: npm run test

  publish:
    needs:
      - lint
      # - test
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    # TODO テストコード書く
    # if: |
    #   github.ref_name == github.event.repository.default_branch
    #   && always()
    #   && (
    #        needs.lint.result == 'success'
    #     || needs.test.result == 'success'
    #   )
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v6
        with:
          path: "**/node_modules"
          key: dev-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache/restore@v6
        with:
          path: packages/**/dist
          key: dist-${{ github.sha }}

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: changesets/action@v1
        with:
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
